### ISSUE TITLE
Request spam

### ISSUE THREAD

**Issue by Quantum-Codes** [Quantum-Codes/Scratch-Profile-Comments#5]
What if someone does request spam... our API will crash? If 2 people requests together? What happens?

**Comment by Sid72020123** [comment]
I don't  know what happens when two people call the API at the same time. I think it would work!

**Comment by Quantum-Codes** [comment]
When 2 people call at once, performance deteriorates so much!!

1 person : 2 to 5 secs
2 people:  6 to 10 secs !!! FOR EACH PERSON!!!!(I threaded)

**Comment by Quantum-Codes** [comment]
@Sid72020123 I think u should watch this repo

**Comment by webdev03** [comment]
Would using a thread for each request help?

**Comment by Quantum-Codes** [comment]
@webdev03 isnt flask automatically threaded?

**Comment by webdev03** [comment]
If you're using the server that comes with Flask you'll get a warning to not use it in production. I'll check if you use that one. I think in the warning there is another module that has a good server.

**Comment by Quantum-Codes** [comment]
Yes, there is a warning to not use in production.

Also, I found out it's multithreaded:
> threaded defaults to True as of Flask 1.0, so for the latest versions of Flask, the default development server will be able to serve multiple clients simultaneously by default. For older versions of Flask, you can explicitly pass threaded=True to enable this behaviour.

**Comment by Quantum-Codes** [comment]
Making read only
