### ISSUE TITLE
Why port 105?

### ISSUE THREAD

**Issue by Quantum-Codes** [Quantum-Codes/Scratch-Profile-Comments#6]
Port 8080 is replit's port. Why 105 (I forgot rip)
I will do a speedtest on both ports and see which is faster in a few days..

**Comment by Sid72020123** [comment]
Ok

**Comment by Sid72020123** [comment]
Check with both the ports

**Comment by Quantum-Codes** [comment]
> Check with both the ports

Why 105 in first place?

**Comment by Sid72020123** [comment]
Because i read somewhere it is good

**Comment by Quantum-Codes** [comment]
Ok.. for #5 ?

**Comment by Quantum-Codes** [comment]
@Sid72020123  speedtest done.

Port 8080:
![Screenshot_20210730-135920_Chrome](https://user-images.githubusercontent.com/87054411/127626145-7be1bfb7-e3cc-4e45-8f41-6ea9de2b0399.jpg)

Port 105:
![Screenshot_20210730-135531_Chrome](https://user-images.githubusercontent.com/87054411/127626349-f7160706-d9da-4f7b-a98d-23beb52c759c.jpg)

IDK why but **Poer 105 is faster**

**Comment by Sid72020123** [comment]
cool!
